version: '3.7'

services:
  go-app:
    container_name: go-app
    image: yanuar/go-app:1.0.1
    build: .
    environment:
      DATABASE_URL: "host=go_db user=postgres password=postgres dbname=postgres sslmode=disable"
    ports:
      - "8000:8000"
    depends_on:
      - go_db
    networks:
      - go-network

  go_db:
    container_name: go_db
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - go-network

  atlas:
    container_name: atlas
    image: arigaio/atlas
    command: [
      "migrate", "apply",
      "--dir", "file:///migrations",
      "--url", "postgres://postgres:postgres@go_db:5432/postgres?sslmode=disable"
    ]
    volumes:
      - ./migrations:/migrations
    depends_on:
      - go_db
    networks:
      - go-network

networks:
  go-network:
    driver: bridge

volumes:
  pgdata: {}
